# Generated by Django 4.2.5 on 2023-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='categories',
            field=models.ManyToManyField(blank=True, to='centrosmain.category', verbose_name='Categorías'),
        ),
    ]
