# Generated by Django 4.2.5 on 2023-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosmain', '0002_centro_email_alter_centro_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='centrosmain.category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='image',
            field=models.ImageField(default='null', upload_to='centros', verbose_name='Imagen'),
        ),
    ]
