# Generated by Django 4.2.5 on 2023-11-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centrosmain', '0003_alter_centro_categories_alter_centro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='centrosImagen')),
                ('centro', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='centrosmain.centro')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
