# Generated by Django 4.2.5 on 2023-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosmain', '0004_imagencentro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagencentro',
            options={},
        ),
        migrations.AddField(
            model_name='centro',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
