# Generated by Django 4.2.5 on 2023-11-14 00:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centrosmain', '0005_alter_imagencentro_options_centro_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Descripcion'),
        ),
    ]
